module.exports = [
    "What are closures with examples?",
    "What is meant by higher-order function?",
    "Difference between Var Let and const.",
    "What is call, apply and bind?",
    "What are the differences between call, apply and bind?",
    "Difference between map and ForEach.",
    "What is Hoisting?",
    "Find the mistake in the given code snippet.",
    "What are hooks?",
    "What are useEffect and useRef?",
    "What is the difference between useState and useEffect?",
    "What is a rest operator?",
    "What is the spread operator?",
    "What is Memoization?",
    "Make a react app in which whatever you type should be visible on the same screen.",
    "What is Redux?",
    "Difference between shallow copy and deep copy.",
    "What will be the output of [] === []?",
    "What is the difference between FrameWork and Library?",
    "What are callback functions?",
    "What do you mean by JSX?",
    "Explain the flow of redux.",
    "Create a timer on the codeSandbox.",
    "How does React work?",
    "Create a form and show the data in the database and display it on Screen as well (including images)",
    "Difference between React and Redux.",
    "What is the difference between redux and context API?",
    "Explain Async Await.",
    "What is Node Js?",
    "What are Promises and its states?",
    "What are hooks?",
    "Explain oops concept.",
    "How to Deploy a MERN project?",
    "Create a stopwatch having start-stop and Reset buttons.",
    "Create a todo application with create, delete and edit functionality.",
    "Create a counter app and manage States using Redux.",
    "Write a code to generate a Random Number.",
    "Difference between states and props.",
    "What is Mounting a component in react?",
    "What is Unmounting a component in react?",
    "What is Local storage?",
    "What is Session storage?",
    "What is the difference between local storage and session storage?",
    "What is useContext Hook?",
    "Write a program in which the background color of the input box changes Randomly on every button Click.",
    "What are the lifecycle methods in react?",
    "What is useMemo?",
    "What is useCallback hook?",
    "What is an Event loop?",
    "Create a React application that generates Random numbers between 5 to 9 on clicking the button.",
    "What is prop Drilling?",
    "Why use Redux?",
    "What is Virtual Dom?",
    "What are classes?",
    "How to manage a State?",
    "Class Components vs Functional Components.",
    "What do mean by controlled and uncontrolled components?",
    "Print the largest Number present in the array.",
    "Generate numbers from 5 to 9 with the click of a button.",
    "What is React-Router-Dom?",
    "Create an Accordion.",
    "Is it possible to create custom hooks in react, if yes then How?",
    "Is React a library?",
    "Optimization techniques in React.",
    "What is middleware? explain with an example.",
    "Why is JavaScript considered a single-threaded language?",
    "What are collections?",
    "What is React fiber?",
    "What are EventEmmitors?",
    "Create an Array of objects and map data in React.",
    "Create a react app such that on button click background color of body should change randomly.",
    "Generate a random Number.",
    "What is the difference between a block element and an inline element?",
    "What is Ref?",
    "Explain React",
    "What is React and how it works?",
    "indexOf() function",
    "Higher order functions.",
    "Map vs ForEach.",
    "Reduce function",
    "What is the work of Splice and Slice",
    "What is mutation in programming?",
    "What are Closures?",
    "What are the lifecycle methods of React functional components?",
    "What are hooks? Explain a few hooks you have used.",
    "What is DNS?",
    "Real DOM vs Virtual DOM.",
    "What is Redux?",
    "Explain the logic behind the Facebook comments and replies section.",
    "Explain Client-server architecture",
    "What are callback functions?",
    "What is React?",
    "What are hooks in React?",
    "What do you mean by class components and functional Components?",
    "Difference between class components and functional components.",
    "What is Redux?",
    "Techniques to prevent Event bubbling",
    "What is Node?",
    "Is Node a single-threaded language or a multi-threaded language?",
    "Implement your own filter function",
    "Questions around 'this' and arrow function?",
    "What is flexbox?",
    "Where do you call the API in a React component if you are doing server-side rendering?",
    "Event bubbling",
    "Event loop?",
    "Negative padding and margins?",
    "Project demo",
    "Show what all things you can do with dev tools in Chrome?",
    "How much memory is allocated to a variable in any language?",
    "Output of this `console.log('3' - '3' + '3' + '3' * '3')`",
    "Implement Promise as a mock API request",
    "What is the difference between visibility: hidden and opacity:0 and display: none",
    "Difference between encoding, encryption, hashing",
    "Any place where encryption is used in web",
    "What are React pure functions?",
    "How does React check if an li is deleted and re-render what?",
    "React 'should component update'?",
    "Should component update in hooks?",
    "Implement your own Array map function",
    "Implement your own Array reduce function",
    "Implement your own Array filter function",
    "What is the difference between Arrow functions and Regular functions in JavaScript?"
  ];
  